### PR TITLE
Added user sign up, user updating, sign in and sign out using a Twitter account.

### PR DESCRIPTION
**Pull request by alexstophel**
I thought this was kind-of a neat way to do authentication. It's fast and allows me to get an avatar without image uploading. What are your thoughts, Chris?

(Sorry about the huge .idea file at the beginning... I forgot to put it in the .gitignore. It's a preference file for RubyMine).

### CODE REVIEW

**Comment by cbeck** [comment]
I will wait to merge until you get those .idea/* files out of the commit so they don't pollute your history.

C

**Comment by alexstophel** [comment]
Done.

**Comment by cbeck** [comment]
Not sure you got this - thanks for doing that. Go ahead and merge it; I m AFK atm.

C

**Comment by cbeck** [comment]
Great, thanks! Go ahead and merge it; I am on the road.

C

**Pull request merged**
